### ISSUE TITLE
An error occurred during the testing of the ProteinMPNN FastRelax Environment. 

### ISSUE THREAD

**Issue by AIM132** [nrbennet/dl_binder_design#83]
An error occurred during the testing of the ProteinMPNN FastRelax Environment. The error is as follows. Does anyone know how to resolve it? Thank you very much

/home/L/dl_binder_design-main/include/importtests/proteinmpnn_importtest.py:11: UserWarning: Import of 'rosetta' as a top-level module is deprecated and may be removed in 2018, import via 'pyrosetta.rosetta'.
  from rosetta import *
┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2024 [Rosetta PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python311.Release 2024.19+release.a34b73c40fe9c61558d566d6a63f803cfb15a4fc 2024-05-02T16:22:03] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags
core.init: Rosetta version: PyRosetta4.conda.linux.cxx11thread.serialization.CentOS.python311.Release r381 2024.19+release.a34b73c a34b73c40fe9c61558d566d6a63f803cfb15a4fc http://www.pyrosetta.org 2024-05-02T16:22:03
core.init: Rosetta extras: [cxx11thread, serialization]
core.init: command: PyRosetta -ex1 -ex2aro -database /home/L/miniconda3/envs/proteinmpnn_binder_design/lib/python3.11/site-packages/pyrosetta/database
basic.random.init_random_generator: 'RNG device' seed mode, using '/dev/urandom', seed=284475851 seed_offset=0 real_seed=284475851 thread_index=0
basic.random.init_random_generator: RandomGenerator:init: Normal mode, seed=284475851 RG_type=mt19937
Traceback (most recent call last):
  File "/home/L/dl_binder_design-main/include/importtests/proteinmpnn_importtest.py", line 15, in <module>
    import torch
  File "/home/L/miniconda3/envs/proteinmpnn_binder_design/lib/python3.11/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/L/miniconda3/envs/proteinmpnn_binder_design/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

**Comment by AIM132** [comment]
I used Conda to build the environment, then installed the package within the environment, and finally solved the problem

**Comment by matiaszunigabustos** [comment]
I edited the .yml file and in the 'dependencies' section, I added the line '- mkl==2024.0' and it worked correctly.

**Comment by EleSpine** [comment]
Hi! I have problems installing the conda environment for ProteinMPNN FastRelax. I added ''https://conda.graylab.jhu.edu'' to my ~/.condarc, but it still cannot solve the environment, it takes forever. Could you share your .yml file?

**Comment by fanch1122** [comment]
> I edited the .yml file and in the 'dependencies' section, I added the line '- mkl==2024.0' and it worked correctly.
mamba install mkl==2024.0  to change version is ok

## for example

- blas               2.128  mkl              conda-forge                                        Cached
  + blas               2.121  mkl              mirrors.ustc.edu.cn/anaconda/cloud/conda-forge       15kB
  - mkl             2024.2.2  ha957f24_16      conda-forge                                        Cached
  + mkl             2024.0.0  ha957f24_49657   mirrors.ustc.edu.cn/anaconda/cloud/conda-forge      126MB
  - mkl-devel       2024.2.2  ha770c72_16      conda-forge                                        Cached
  + mkl-devel       2024.0.0  ha770c72_49657   mirrors.ustc.edu.cn/anaconda/cloud/conda-forge       32kB
  - mkl-include     2024.2.2  ha957f24_16      conda-forge                                        Cached
  + mkl-include     2024.0.0  ha957f24_49657   mirrors.ustc.edu.cn/anaconda/cloud/conda-forge      768kB
